# Generated by Django 5.1.2 on 2024-10-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_librarymodel_studentmodel_coursemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='librarymodel',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='student_id',
        ),
    ]
