# Generated by Django 5.1.2 on 2024-10-17 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_academiccalendar_teachermodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.studentmodel'),
        ),
    ]
